apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: lokicyberbytes/flask-app:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: local-storage
          mountPath: /app/files  # Inside the container
      volumes:
      - name: local-storage # minikube mount D:\file-system\file_storage:/mnt/local-dir
        hostPath:
          path: /mnt/local-dir  # Path to local directory on your local machine or Kubernetes node
          type: DirectoryOrCreate
