apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80         # Exposed port for the Flask app kubectl port-forward service/flask-app-service 5000:80
    targetPort: 5000 # Flask app's internal port
    nodePort: 30001  # Port on your Minikube node to access the service
